# Generated by Django 4.2.2 on 2023-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_first_name', models.CharField(max_length=30)),
                ('auth_email', models.EmailField(max_length=254)),
                ('Title', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=100)),
                ('Publication_year', models.IntegerField(default=0)),
                ('Issue_status', models.BooleanField(default=False)),
                ('Issued_roll_no', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Book',
            },
        ),
    ]
